package com.agus.sonora;

import android.Manifest;
import android.content.ContentUris;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.provider.MediaStore;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Everything the user can play: songs on the device, the online catalog, liked songs and
 * user playlists. Likes and playlists are persisted in SharedPreferences as JSON.
 */
public final class Library {

    public interface Listener {
        void onLibraryChanged();
    }

    private static Library sInstance;

    public static synchronized Library get(Context context) {
        if (sInstance == null) sInstance = new Library(context.getApplicationContext());
        return sInstance;
    }

    private final Context app;
    private final SharedPreferences prefs;
    private final Handler main = new Handler(Looper.getMainLooper());
    private final List<Listener> listeners = new CopyOnWriteArrayList<>();

    private List<Track> local = new ArrayList<>();
    private final List<Track> online = new ArrayList<>();
    private final Map<String, Track> byKey = new HashMap<>();
    private final List<String> liked = new ArrayList<>();
    private final LinkedHashMap<String, List<String>> playlists = new LinkedHashMap<>();
    private boolean loading;
    private boolean loadedOnce;

    private Library(Context app) {
        this.app = app;
        this.prefs = app.getSharedPreferences("library", Context.MODE_PRIVATE);
        buildOnlineCatalog();
        restore();
    }

    // ---------------------------------------------------------------- catalog

    private void buildOnlineCatalog() {
        // Free, openly licensed demo tracks generated by SoundHelix; streamed over https.
        String[] moods = {
                "Amanecer", "Ruta nocturna", "Neón", "Marea", "Cumbre", "Eclipse",
                "Latido", "Horizonte", "Brisa", "Órbita", "Aurora", "Pulso",
                "Vértigo", "Desierto", "Lluvia", "Constelación"
        };
        for (int i = 1; i <= 16; i++) {
            String url = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-" + i + ".mp3";
            Track t = new Track(url, moods[i - 1] + " (SoundHelix " + i + ")",
                    "SoundHelix", i <= 8 ? "Descubrimientos Vol. 1" : "Descubrimientos Vol. 2",
                    -1, 0, true, 0);
            online.add(t);
            byKey.put(url, t);
        }
    }

    public static boolean hasAudioPermission(Context c) {
        if (Build.VERSION.SDK_INT < 23) return true;
        String p = Build.VERSION.SDK_INT >= 33
                ? Manifest.permission.READ_MEDIA_AUDIO
                : Manifest.permission.READ_EXTERNAL_STORAGE;
        return c.checkSelfPermission(p) == PackageManager.PERMISSION_GRANTED;
    }

    /** Re-scans the device's music in the background, then notifies listeners. */
    public void reloadLocal() {
        if (loading || !hasAudioPermission(app)) {
            notifyChanged();
            return;
        }
        loading = true;
        new Thread(new Runnable() {
            @Override
            public void run() {
                final List<Track> found = queryDevice();
                main.post(new Runnable() {
                    @Override
                    public void run() {
                        for (Track t : local) byKey.remove(t.key);
                        local = found;
                        for (Track t : local) byKey.put(t.key, t);
                        loading = false;
                        loadedOnce = true;
                        notifyChanged();
                    }
                });
            }
        }, "library-scan").start();
    }

    private List<Track> queryDevice() {
        List<Track> out = new ArrayList<>();
        Uri base = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;
        String[] cols = {
                MediaStore.Audio.Media._ID,
                MediaStore.Audio.Media.TITLE,
                MediaStore.Audio.Media.ARTIST,
                MediaStore.Audio.Media.ALBUM,
                MediaStore.Audio.Media.ALBUM_ID,
                MediaStore.Audio.Media.DURATION,
                MediaStore.Audio.Media.DATE_ADDED,
        };
        Cursor c = null;
        try {
            c = app.getContentResolver().query(base, cols,
                    MediaStore.Audio.Media.IS_MUSIC + " != 0", null,
                    MediaStore.Audio.Media.TITLE + " COLLATE NOCASE ASC");
            if (c == null) return out;
            while (c.moveToNext()) {
                long id = c.getLong(0);
                long dur = c.getLong(5);
                if (dur > 0 && dur < 5000) continue; // skip notification blips
                Uri uri = ContentUris.withAppendedId(base, id);
                out.add(new Track(uri.toString(), c.getString(1), c.getString(2),
                        c.getString(3), c.getLong(4), dur, false, c.getLong(6)));
            }
        } catch (Exception ignored) {
            // A broken MediaStore should never crash the app; show what we have.
        } finally {
            if (c != null) c.close();
        }
        return out;
    }

    public boolean isLoading() {
        return loading;
    }

    public boolean loadedOnce() {
        return loadedOnce;
    }

    public List<Track> localTracks() {
        return Collections.unmodifiableList(local);
    }

    public List<Track> onlineTracks() {
        return Collections.unmodifiableList(online);
    }

    public List<Track> allTracks() {
        List<Track> all = new ArrayList<>(local);
        all.addAll(online);
        return all;
    }

    public List<Track> recentlyAdded(int max) {
        List<Track> l = new ArrayList<>(local);
        Collections.sort(l, new Comparator<Track>() {
            @Override
            public int compare(Track a, Track b) {
                return Long.compare(b.dateAdded, a.dateAdded);
            }
        });
        return l.size() > max ? new ArrayList<>(l.subList(0, max)) : l;
    }

    public Track find(String key) {
        return byKey.get(key);
    }

    // ---------------------------------------------------------------- search & grouping

    static String fold(String s) {
        String n = Normalizer.normalize(s, Normalizer.Form.NFD);
        return n.replaceAll("\\p{M}+", "").toLowerCase(Locale.ROOT);
    }

    public List<Track> search(String query) {
        String q = fold(query.trim());
        List<Track> out = new ArrayList<>();
        if (q.isEmpty()) return out;
        for (Track t : allTracks()) {
            if (fold(t.title).contains(q) || fold(t.artist).contains(q) || fold(t.album).contains(q)) {
                out.add(t);
            }
        }
        return out;
    }

    /** Groups all tracks by artist (or album when byAlbum), keys sorted alphabetically. */
    public LinkedHashMap<String, List<Track>> group(boolean byAlbum) {
        Map<String, List<Track>> m = new HashMap<>();
        for (Track t : allTracks()) {
            String k = byAlbum ? t.album : t.artist;
            List<Track> l = m.get(k);
            if (l == null) m.put(k, l = new ArrayList<>());
            l.add(t);
        }
        List<String> keys = new ArrayList<>(m.keySet());
        Collections.sort(keys, String.CASE_INSENSITIVE_ORDER);
        LinkedHashMap<String, List<Track>> out = new LinkedHashMap<>();
        for (String k : keys) out.put(k, m.get(k));
        return out;
    }

    // ---------------------------------------------------------------- likes

    public boolean isLiked(Track t) {
        return t != null && liked.contains(t.key);
    }

    public void toggleLike(Track t) {
        if (t == null) return;
        if (!liked.remove(t.key)) liked.add(0, t.key);
        save();
        notifyChanged();
    }

    public List<Track> likedTracks() {
        return resolve(liked);
    }

    // ---------------------------------------------------------------- playlists

    public List<String> playlistNames() {
        return new ArrayList<>(playlists.keySet());
    }

    public List<Track> playlist(String name) {
        List<String> keys = playlists.get(name);
        return keys == null ? new ArrayList<Track>() : resolve(keys);
    }

    /** @return false if a playlist with that name already exists. */
    public boolean createPlaylist(String name) {
        if (name == null) return false;
        name = name.trim();
        if (name.isEmpty() || name.equals("__order") || playlists.containsKey(name)) return false;
        playlists.put(name, new ArrayList<String>());
        save();
        notifyChanged();
        return true;
    }

    public void deletePlaylist(String name) {
        playlists.remove(name);
        save();
        notifyChanged();
    }

    /** @return false if the track was already in it. */
    public boolean addToPlaylist(String name, Track t) {
        List<String> keys = playlists.get(name);
        if (keys == null || keys.contains(t.key)) return false;
        keys.add(t.key);
        save();
        notifyChanged();
        return true;
    }

    public void removeFromPlaylist(String name, Track t) {
        List<String> keys = playlists.get(name);
        if (keys != null && keys.remove(t.key)) {
            save();
            notifyChanged();
        }
    }

    private List<Track> resolve(List<String> keys) {
        List<Track> out = new ArrayList<>();
        for (String k : keys) {
            Track t = byKey.get(k);
            if (t != null) out.add(t);
        }
        return out;
    }

    // ---------------------------------------------------------------- persistence

    private void restore() {
        try {
            JSONArray l = new JSONArray(prefs.getString("liked", "[]"));
            for (int i = 0; i < l.length(); i++) liked.add(l.getString(i));
            JSONObject p = new JSONObject(prefs.getString("playlists", "{}"));
            JSONArray order = p.optJSONArray("__order");
            List<String> names = new ArrayList<>();
            if (order != null) {
                for (int i = 0; i < order.length(); i++) names.add(order.getString(i));
            } else {
                Iterator<String> it = p.keys();
                while (it.hasNext()) names.add(it.next());
            }
            for (String name : names) {
                JSONArray a = p.optJSONArray(name);
                if (a == null || "__order".equals(name)) continue;
                List<String> keys = new ArrayList<>();
                for (int i = 0; i < a.length(); i++) keys.add(a.getString(i));
                playlists.put(name, keys);
            }
        } catch (Exception ignored) {
            // Corrupt prefs: start empty rather than crash.
        }
    }

    private void save() {
        try {
            JSONObject p = new JSONObject();
            JSONArray order = new JSONArray();
            for (Map.Entry<String, List<String>> e : playlists.entrySet()) {
                p.put(e.getKey(), new JSONArray(e.getValue()));
                order.put(e.getKey());
            }
            p.put("__order", order);
            prefs.edit()
                    .putString("liked", new JSONArray(liked).toString())
                    .putString("playlists", p.toString())
                    .apply();
        } catch (Exception ignored) {
        }
    }

    // ---------------------------------------------------------------- listeners

    public void addListener(Listener l) {
        listeners.add(l);
    }

    public void removeListener(Listener l) {
        listeners.remove(l);
    }

    private void notifyChanged() {
        for (Listener l : listeners) l.onLibraryChanged();
    }
}
