"""Strings carried over from earlier versions (chat lines, signs, messages)."""

KEPT = {
    'hl.ambience.whisper': ('§8§o...%s...', '§8§o...%s...'),
    'hl.hb.torches': ('§4Tus antorchas se han vuelto rojas.', '§4Your torches have turned red.'),
    'hl.sign.1': ('DETRÁS\\nDE TI', 'BEHIND\\nYOU'),
    'hl.sign.2': ('TE ESTOY\\nVIENDO', 'I SEE\\nYOU'),
    'hl.sign.3': ('VETE', 'LEAVE'),
    'hl.sign.4': ('NO ESTÁS\\nSOLO', 'YOU ARE\\nNOT ALONE'),
    'hl.sign.5': ('¿POR QUÉ\\nSIGUES\\nAQUÍ?', 'WHY ARE\\nYOU STILL\\nHERE?'),
    'hl.sign.6': ('NO HAY\\nSALIDA', 'NO WAY\\nOUT'),
    'hl.fog.start': ('§7Una niebla espesa lo cubre todo...', '§7A thick fog covers everything...'),
    'hl.fog.end': ('§7La niebla se disipa.', '§7The fog lifts.'),
    'hl.fog.chase': ('§4§l¡CORRE!', '§4§lRUN!'),
    'hl.fog.lost': ('§7Le has perdido. Por ahora.', '§7You lost him. For now.'),
    'hl.fog.knock': ('§7§oAlguien está llamando a la puerta.', '§7§oSomeone is knocking at the door.'),
    'hl.cave.chase': ('§4§lTe ha encontrado.', '§4§lIt found you.'),
    'hl.flash.dweller': ('§7La luz lo ahuyenta.', '§7The light drives it away.'),
    'hl.flash.fog': ('§4La luz no le detiene.', "§4The light doesn't stop him."),
    'hl.null.crash.title': ('Minecraft', 'Minecraft'),
    'hl.null.crash.body': ('Minecraft no responde.\\n\\nSi cierras el programa, podrías perder información.\\n\\n§8null', 'Minecraft is not responding.\\n\\nIf you close the program, you might lose information.\\n\\n§8null'),
    'hl.null.crash.wait': ('Esperar', 'Wait'),
    'hl.null.crash.close': ('Cerrar el programa', 'Close the program'),
    'hl.null.chat.1': ('null', 'null'),
    'hl.null.chat.2': ('§knull§r null §knull', '§knull§r null §knull'),
    'hl.null.chat.3': ('¿Por qué sigues aquí, %s?', 'Why are you still here, %s?'),
    'hl.null.chat.4': ('Este mundo ya no es tuyo.', "This world isn't yours anymore."),
    'hl.null.chat.5': ('No deberías haber instalado esto.', "You shouldn't have installed this."),
    'hl.null.chat.6': ('Te veo, %s.', 'I see you, %s.'),
    'hl.int.low': ('Baja', 'Low'),
    'hl.int.normal': ('Normal', 'Normal'),
    'hl.int.high': ('Alta', 'High'),
    'hl.int.nightmare': ('§4Pesadilla', '§4Nightmare'),
    'hl.fake.hello.1': ('hola', 'hi'),
    'hl.fake.hello.2': ('hola %s jaja', 'hi %s lol'),
    'hl.fake.hello.3': ('holaa', 'hiii'),
    'hl.fake.hello.4': ('alguien quiere jugar?', 'anyone wanna play?'),
    'hl.fake.chat.1': ('q bonito mundo', 'nice world'),
    'hl.fake.chat.2': ('voy a buscar diamantes', 'gonna look for diamonds'),
    'hl.fake.chat.3': ('tienes comida?', 'got any food?'),
    'hl.fake.chat.4': ('construyamos una casa', 'lets build a house'),
    'hl.fake.chat.5': ('jaja', 'lol'),
    'hl.fake.chat.6': ('espera q pico esto', 'wait lemme mine this'),
    'hl.fake.chat.7': ('mi internet va lento xd', 'my internet is so slow xd'),
    'hl.fake.chat.8': ('de donde eres %s?', 'where r u from %s?'),
    'hl.fake.gift': ('toma, para ti', 'here, for you'),
    'hl.fake.copy': ('yo tambien', 'me too'),
    'hl.fake.mimic.1': ('jaja te copio', 'lol im copying u'),
    'hl.fake.mimic.2': ('%s', '%s'),
    'hl.fake.mimic.3': ('hago lo mismo q tu', 'i do what u do'),
    'hl.fake.mimic.4': ('mira, somos iguales', "look, we're the same"),
    'hl.fake.mimic.5': ('por q haces eso?', 'why r u doing that?'),
    'hl.fake.mimic.6': ('haz otra cosa %s', 'do something else %s'),
    'hl.fake.creepy.1': ('...', '...'),
    'hl.fake.creepy.2': ('deja de mirarme', 'stop looking at me'),
    'hl.fake.creepy.3': ('no soy un jugador', 'im not a player'),
    'hl.fake.creepy.4': ('sigues ahi, %s?', 'still there, %s?'),
    'hl.fake.creepy.5': ('ya casi', 'almost'),
    'hl.fake.creepy.6': ('no hay nadie mas en este mundo', 'theres nobody else in this world'),
    'hl.fake.hit': ('oye! para', 'hey! stop'),
    'hl.fake.reveal': ('ya no tengo que fingir', 'i dont have to pretend anymore'),
    'hl.presence.death': ('%s murió', '%s died'),
    'hl.presence.death2': ('§8§o...todavía no.', '§8§o...not yet.'),
    'hl.blood.title': ('§4§lLA NOCHE ROJA', '§4§lTHE RED NIGHT'),
    'hl.blood.sub': ('§cNo duermas. No mires atrás.', "§cDon't sleep. Don't look back."),
    'hl.blood.end': ('§7Amanece. Por ahora.', '§7Dawn. For now.'),
}
